production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: resume_development
  pool: 5
  host: localhost
  username: postgres
  password: root

test:
  adapter: postgresql
  database: resume_test
  pool: 5
  host: localhost
  username: postgres
  password: root
